/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sidata.panel;

/**
 *
 * @author syubban
 */
public class ViewReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDataMaster
     */
    public ViewReportPanel() {
        initComponents();
//        myCustomInitComponents();
    }
    
    private void myCustomInitComponents(){
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewReportLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        viewReportLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewReportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewReportLabel.setText("View Report");
        viewReportLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        viewReportLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(viewReportLabel)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(viewReportLabel)
                .addContainerGap(420, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel viewReportLabel;
    // End of variables declaration//GEN-END:variables
}
